[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.18.0"

[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "0.14.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.12"


[[override]]
  name = "k8s.io/client-go"
  version = "v9.0.0"

[prune]
  go-tests = true
  unused-packages = true
